// PLACEHOLDER — regenerated by `pnpm db:types` once Supabase Local is running
// (Task 1.6). Until then, an empty Database interface keeps the typed-client
// module compilable without forcing a Docker dependency on contributors who
// only want to read or build the lib.
//
// biome-ignore-all lint/suspicious/noEmptyInterface: placeholder, regenerated.

export interface Database {}
